name: Publish

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install lektor

      # Lektor build will store the build files in a temporary directory for later.
      # We want to keep the readme etc updated also!
      - name: Build with Lektor
        run: |
          lektor --project 'Australian Digital Observatory' build --output-path $RUNNER_TEMP/build
          cp .gitignore README.md LICENSE $RUNNER_TEMP/build

      - name: Setup git config
        run: |
          git config user.name "lektor deploy"
          git config user.email "<>"

      - name: Switch to gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      # Gets the built website files from the temporary directory and commits them to gh-pages branch
      - name: Commit build to gh-pages
        run: |
          cp -r $RUNNER_TEMP/build/* .
          git add *
          git commit -m "Automated commit for deploy"
          git push origin gh-pages
